---
environments:
  local: {}
  dev: {}
  qa: {}
  staging: {}
  production: {}
---
helmfiles:
  - metrics-server/helmfile.yaml
  - cert-manager/helmfile.yaml
  - eck-operator/helmfile.yaml
  - cert-manager-issuers/helmfile.yaml
  - traefik/helmfile.yaml
