repositories:
  - name: jetstack
    url: https://charts.jetstack.io

environments:
  local:
  dev:
  qa:
  staging:
  production:
---
releases:
  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: jetstack/cert-manager
    version: v1.11.1
    values:
      - values.yml.gotmpl
