---
repositories:
  - name: traefik
    url: https://traefik.github.io/charts

environments:
  local: {}
  dev: {}
  qa: {}
  staging: {}
  production: {}
---
releases:
  - name: traefik
    namespace: traefik
    createNamespace: true
    chart: traefik/traefik
    version: 37.1.2
    values:
      - values.yml.gotmpl
