apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: global-cert-issuer
spec:
  acme:
    email: pwarrier3@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: global-cert-issuer
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token
