---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: global-cert-issuer-letsencrypt-staging
spec:
  acme:
    email: pwarrier3@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: global-cert-issuer-letsencrypt-staging
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: global-cert-issuer-letsencrypt-prod
spec:
  acme:
    email: pwarrier3@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: global-cert-issuer-letsencrypt-prod
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token
