dnsNames:
  - ca-local.stratosboard.co
  - step-ca.step-ca.svc.cluster.local

intermediateCA: |
  -----BEGIN CERTIFICATE-----
  MIICBjCCAaugAwIBAgIRAMOUJ4UshpTjoPQO0K5O+mkwCgYIKoZIzj0EAwIwTDEg
  MB4GA1UEChMXU3RyYXRvc2JvYXJkIENBIC0gTG9jYWwxKDAmBgNVBAMTH1N0cmF0
  b3Nib2FyZCBDQSAtIExvY2FsIFJvb3QgQ0EwHhcNMjMwNDA5MTQzMTE4WhcNMzMw
  NDA2MTQzMTE4WjBUMSAwHgYDVQQKExdTdHJhdG9zYm9hcmQgQ0EgLSBMb2NhbDEw
  MC4GA1UEAxMnU3RyYXRvc2JvYXJkIENBIC0gTG9jYWwgSW50ZXJtZWRpYXRlIENB
  MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEUWmr4Z9ieNiToIwt8Je6hiXPpzih
  esejAVArOxRRLu1TtN1oASKWgtKOmhpyPzhpb5HXzIaxWlS0m8hGuJjZ76NmMGQw
  DgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFMmn
  InfLv1U6WLbCNYclRBCzJgYSMB8GA1UdIwQYMBaAFLPM0nWH9FnK8NylQ56fGQdZ
  N9e0MAoGCCqGSM49BAMCA0kAMEYCIQDk1goENweu7pgIaPqQcYRG+oeEDHuIzM6x
  d+EdMJszGAIhALMM/svucxxRCxwtn/rOVRug+7CXUVKJLOxs+frfPJVH
  -----END CERTIFICATE-----

rootCA: |
  -----BEGIN CERTIFICATE-----
  MIIB3TCCAYKgAwIBAgIRAMSDDtq1Mpa/8JxAr2ilwMswCgYIKoZIzj0EAwIwTDEg
  MB4GA1UEChMXU3RyYXRvc2JvYXJkIENBIC0gTG9jYWwxKDAmBgNVBAMTH1N0cmF0
  b3Nib2FyZCBDQSAtIExvY2FsIFJvb3QgQ0EwHhcNMjMwNDA5MTQzMTE3WhcNMzMw
  NDA2MTQzMTE3WjBMMSAwHgYDVQQKExdTdHJhdG9zYm9hcmQgQ0EgLSBMb2NhbDEo
  MCYGA1UEAxMfU3RyYXRvc2JvYXJkIENBIC0gTG9jYWwgUm9vdCBDQTBZMBMGByqG
  SM49AgEGCCqGSM49AwEHA0IABJE9PYagLbJ5xFEf5DTRVBD/aj8A2aOZFIACEIm+
  n+hAVseidWZVGy6M2Qj4E3LVJVNr6pCbz0WLtJ6YE49Npu+jRTBDMA4GA1UdDwEB
  /wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEBMB0GA1UdDgQWBBSzzNJ1h/RZyvDc
  pUOenxkHWTfXtDAKBggqhkjOPQQDAgNJADBGAiEAtXj7VM2rXI4hoR0MxASwk0hm
  0BbqSrSe2IbvhRBSwYQCIQC+2RVE38tBEihBoXU5dIuCP/H6fIwDBQrzGxO4oWQT
  nw==
  -----END CERTIFICATE-----

fingerprint: 5d2da300abed375e643be2aca793e703a1e474fade16860791313a40e3a127b6
