secretCloudflareAPIToken: ENC[AES256_GCM,data:vW26mNLeaVmHXIzWZSF7Xb3nqD/iqB7v90Ivlz77GeBWN24xqCIgmQ==,iv:otrJP2nYDh6C0HexuZ2eddJrUM+hb5GOWRdLyoM41e4=,tag:iy8fcQjhWL1XuPAQPgHD0g==,type:str]
sops:
    lastmodified: "2025-05-01T13:48:50Z"
    mac: ENC[AES256_GCM,data:QnY9H9bUBgM3kKXGLoGvJX4nkkCecH1gdDlPiL4ko3TR5vx1p6pbOMU2JMsuZN0g2GzUHXJgWm9trVj1EuAlCSRtOmORzs35cQ7Wa6VXUrvByXxHiiEyKLcCjCugMWRqbchmm2glEC9VEdA3SENfnPzK+1Vuzvpg3iTtiuO/6XQ=,iv:8IYOLnPrg0rsloSZ9EEZ+QViLfqD0w+GWvOZOMjvpxA=,tag:t6fgZ//q265DFZwFjfNoEg==,type:str]
    pgp:
        - created_at: "2024-03-12T02:43:58Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyEc+rhwob+UAQ//eDsaKExiC8D8Nn8fCLCim83JV7MB5Dfwy/w+d5w20gvv
            9p/f7SFgncburPqWFdT/k3GhkBRdCKN5E/iqvERz45iJDRtGyD+oxiuT8x4jAUEc
            Z4IDKqOEwBzVt3aQn86O0wA2aOQnO82OapsllS/53MeWCjMeUA1aO8+yQMMk9d8M
            s++/2bfe4fbiVOl+t0OOZRV7tPRXmLfwGLcXwEgooY1uXOqT24oQ90BM1kFVTyLz
            0vYtEVKxhQ2AOBZW2vfb6CKI4FKBolqyh30OjQfV8Msv8GGtcMEkBT1tJNiub5o6
            fgzbHKk6pUVqMz9CgpWBb387ZsgIK8U0GP4Q4SjC+SmqgPLUtFV3YdJdV2SojS48
            7jfuN8cdTRW4QTahpYZbEuZBpE6IWbunKd1waiFq07thl6a/ChufB2XYD3baYTHU
            GdeMjQlWRSvga0tTMGbyToOoF+Fjar4PBCHgLF8LtbkGkpuZBU+eK/fwXzWuIW3G
            szyKgUV4g2bNGkvEqwKT2J7mAPo3AZaa7lN+Bn8MxSDpMeqD44MrD8/MLx+4u9xz
            LJVA1q8lXbM1GtGm4Dq2n97ZB+b9a+SpA+1qBQPI53llrCkORBQ64daMDM9QL+mf
            D/Jm7B/c8ulwSJQzUNVuziRzwSHPhjyAcH68WBWZDGSCiq/V4ABmhNvdTtlQCQLS
            XgGg1giu+JkccSJecSZy+jHYiaVS8tXUjZTi1i8D/9sgHEZtgUqMIWebmA8MUzVT
            pQuCcNvXugkEXQ+axIMWrd56xFxf24Kmgq6SQroJsQmhCixFstqOiQSnASWVQfQ=
            =ovyz
            -----END PGP MESSAGE-----
          fp: BC3C31A31EABBDCDE74F96CFFF036672B23251E7
    unencrypted_suffix: _unencrypted
    version: 3.10.2
